### ISSUE TITLE
Example requested: Arranging figures and supplemental figures

### ISSUE THREAD

**Issue by dhicks** [iagopinal/figure-table-formatter#1]
I found this project from your comment on [this Quarto question](https://github.com/quarto-dev/quarto-cli/discussions/9934). I'm a little confused how to use it, though. 

Here's my use case: I'm preparing an article for a journal that wants figures and tables at the end of the Word doc. (Apparently they "don't accept PDFs.")  I also have supplemental text, figures, and tables in the same `qmd` file, to facilitate cross-referencing and a combined reference list.  

So I need things in this order: 

1. Main body text
2. References
3. Main figures and tables
4. SI text, figures, and tables

Based on the example in the README, I can start with something like this: 

```
---
filters:
  - iagopinal/figure_table_formatter
---

# Introduction

This document discusses several experiments. We will refer to various figures and tables.

In Experiment 1, we can see the results in @fig:experiment1 and @fig:experiment2. Also, @fig:experiment4 illustrates an important finding.

The analysis is summarized in @tbl:results and detailed further in @tbl:summary.

Supplementary details can be found in @sec-supp, @supfig:extra1, and @suptbl:appendixA. 

# References

::: {#refs}
:::

# Supplement {#sec-supp}
```

But I'm not sure how to indicate where the figures and tables should be placed.

**Comment by iagopinal** [comment]
Hi, you just have to place a placeholder:
- &&&fig,tbl&&& will place the figures and then the tables
- &&&fig-tbl&&& will place the figures and the tables as they were referenced in the text
- &&&supfig,suptbl&&& will place the supplementary figures and then the supplementary tables
- &&&supfig-suptbl&&& will place the supplementary figures and tables as they were cited.

You can combine them as you want, for example:
- &&&fig-tbl,supfig,suptbl&&& will plce the figures and the tables as they were cited in the text, then the supp figs and after them the supp tables. No spaces within the tag.

**Comment by dhicks** [comment]
Here's an attempt at a MWE: 
````
---
filters:
  - iagopinal/figure-table-formatter
---

foo @fig:mtcars

```{r}
#| label: fig:mtcars
#| fig-cap: "marzey dotes and dozey dotes"

plot(mtcars$hp, mtcars$mpg)
```

bar

&&&fig&&&
````

Expected behavior: the plot appears below "bar"

Observed behavior: the plot appears above "bar"

The filter is running, with this output: 
````
INFO: html
INFO: Running format_citations.
INFO: Sorted IDs: ['fig:mtcars']
INFO: Counters: {'fig': 1, 'tbl': 0, 'supfig': 0, 'suptbl': 0}
INFO: Placeholder: fig
WARNING: No valid items to insert for placeholder: fig
Output created: test.html
````

**Comment by iagopinal** [comment]
Try like this. The call to the figure has to be prepended with a #. You can include it in the fig-cap, no need for the label.

````
---
filters:
  - iagopinal/figure-table-formatter
---

foo @fig:mtcars

```{r}
#| fig-cap: "#fig:mtcars marzey dotes and dozey dotes"

plot(mtcars$hp, mtcars$mpg)
```

bar

&&&fig&&&
````

This works in my hands, :)
